name: 📚 Documentation
description: Report an issue and help us improve the documentation（报告问题并帮助我们改进文档）
labels: "type: docs"

body:
  - type: textarea
    attributes:
      label: 📚 The doc issue
      description: |
        Provide a clear and concise description of the content in https://midwayjs.org. There may be some text description errors or link errors.
        
        提供 https://midwayjs.org 中的内容的清晰简洁的描述。可能是一些文本描述错误或链接错误。
    validations:
      required: true
  - type: textarea
    attributes:
      label: Suggest a potential alternative/fix（建议潜在的替代/修复）
      description: >
        Tell us how we could improve the documentation in this regard.
        
        告诉我们如何在这方面改进文档。
  - type: markdown
    attributes:
      value: >
        Thanks for contributing 🎉!
        
        感谢您的贡献 🎉！
